name: Daily Blog Summary

on:
  schedule:
    - cron: '0 23 * * *'  # 한국시간 오전 8시
  workflow_dispatch:      # 우리가 원할 때 수동으로 버튼 눌러 실행하기

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 필요한 프로그램 설치하기
        # 앞에 있던 '블로그 요약/' 글자를 지웠어요!
        run: pip install -r requirements.txt

      - name: 요약 프로그램 실행하기
        env:
            SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
            SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            EMAIL_TO: ${{ secrets.EMAIL_TO }}
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python daily_blog_summary.py
      
